//-----------------------------------------------------------------------
// <copyright file="BatchResult.cs" company="Hibernating Rhinos LTD">
//     Copyright (c) Hibernating Rhinos LTD. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
using System;
using Raven.Json.Linq;

namespace Raven.Light.Commands
{
	/// <summary>
	/// The result of a single operation inside a batch
	/// </summary>
	public class BatchResult
	{
		/// <summary>
		/// Gets or sets the etag generated by the etag (if applicable)
		/// </summary>
		/// <value>The etag.</value>
		public Guid? Etag { get; set; }
		
		/// <summary>
		/// Gets or sets the key of the document
		/// </summary>
		/// <value>The key.</value>
		public string Key { get; set; }
	}
}
